FROM python:3.10-slim

RUN apt-get update
RUN apt-get install python3-dev default-libmysqlclient-dev build-essential -y

RUN pip install pipenv

WORKDIR /app

COPY Pipfile .
COPY Pipfile.lock .

RUN PIPENV_VENV_IN_PROJECT=1 pipenv install --deploy

ENV PATH="/app/.venv/bin:$PATH"

COPY diabetesapp.py rf_model.pkl ./
COPY /db ./db
COPY /security ./security

EXPOSE 3000
CMD ["uvicorn", "diabetesapp:app", "--host", "0.0.0.0", "--port", "3000"]
